FROM jenkins/jenkins:2.60.3-alpine
MAINTAINER Chandra Sekhar Eswa

# Install Jenkins plugins
RUN /usr/local/bin/install-plugins.sh \
active-directory:2.0 \
anchore-container-scanner \
locale \
credentials-binding \
next-executions \
build-environment \
git-client \
cloudbees-folder \
junit \
ansicolor \
subversion \
copyartifact \
build-timeout \
ssh-agent \
docker-plugin \
gitlab-plugin \
ws-cleanup \
robot \
timestamper \
slack \
categorized-view \
maven-plugin \
ssh-slaves \
git \
role-strategy \
matrix-auth \
email-ext \
mailer \
xvfb \
workflow-aggregator \
blueocean \
jobConfigHistory \
sonar \
parameterized-trigger \
saferestart \
simple-theme-plugin \
build-blocker-plugin \
envinject \
pipeline-maven \
nexus-artifact-uploader \
pipeline-utility-steps

